baseURL = '/'
locale = 'en-us'
title = 'Foran'
theme = 'wf'
relativeURLs = true

[module]
[[module.mounts]]
  source = '../reports/'
  target = 'content'
[[module.mounts]]
  source = "../images/"
  target = "static/images"
